apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-k8s
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-k8s
  template:
    metadata:
      labels:
        app: spring-k8s
    spec:
      containers:
        - name: spring-k8s
          imagePullPolicy: Always
          image: canmogol/spring-k8s:0.0.1
          env:
#            - name: SPRING_CONFIG_LOCATION # if you set the configuration file, the ConfigMap changes are not loaded!
#              value: "/opt/spring-k8s/application.yaml"
            - name: LOGGING_LEVEL_ROOT
              value: "DEBUG"
            - name: SERVER_PORT
              value: "80"
#          volumeMounts:
#            - mountPath: "/opt/spring-k8s/"
#              name: spring-k8s-config
      serviceAccountName: config-reader
#      volumes:
#        - name: spring-k8s-config
#          configMap:
#            name: spring-k8s-config
#            items:
#              - key: application.yaml
#                path: application.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: spring-k8s-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: spring-k8s
  ports:
    - name: http
      port: 80
      targetPort: 80

